### ISSUE TITLE
About 'RGB no more: Minimally-decoded JPEG Vision Transformers'

### ISSUE THREAD

**Issue by kun-dragon** [JeongsooP/JeongsooP.github.io#1]
That is a good job! I'm very interested in the novel idea. And I have some questions:
**1.** If the input is image is too big, we need to crop and resize the image to a fixed size (224x224), will the croping and the resizing in DCT domain make the whole classification pipeline lower than that in RGB domain?
**2.** Do you try the novel idea in ViT-base or ViT-large model?
**3.** Do you try the novel idea in MAE to get a pretrained model in DCT domain?

**Comment by kun-dragon** [comment]
And could you share the code about the paper?

**Comment by JeongsooP** [comment]
Sorry for the late reply, kun-dragon. I do not monitor github issues for my personal website; it is recommended that you contact me through the email listed on the website, under my name.

1. It is possible that if the image is too big, the resizing could become a bottleneck. This is because resizing is done through matrix multiplications. Cropping on the other hand, should be negligibly fast.
2. I haven't thoroughly tested my model on ViT-B or L due to resource constraints. If you have the resources, it would be awesome to do hyperparameter search on them.
3. No, I haven't tried this method on MAE. It would be amazing if you could make it work on MAE.
4. I am working on the code release; I will release them along with a twitter thread when ready.
